# Generated by Django 5.0.6 on 2024-09-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Description', models.CharField(max_length=100)),
                ('Phase', models.CharField(max_length=10)),
                ('Sponser_Name', models.CharField(max_length=20)),
            ],
        ),
    ]
